// Generated by CoffeeScript 1.9.1
module.exports = {
  unary: {
    localstorage: function(exe, params) {
      var getsource;
      getsource = exe.build(params.__s);
      return function(cb) {
        return getsource(function(err, source) {
          var e;
          if (err != null) {
            return cb(err);
          }
          try {
            return cb(null, localStorage[source]);
          } catch (_error) {
            e = _error;
            return cb(e);
          }
        });
      };
    }
  }
};
