// Generated by CoffeeScript 1.9.1
module.exports = function(query, cb) {
  var key, result, value;
  result = {};
  for (key in query) {
    value = query[key];
    result[key] = JSON.parse(localStorage.getItem(value.__params));
  }
  cb(null, result);
  return function() {
    return clearTimeout(handle);
  };
};
